//go:build !windows

package redteam

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"
)

// esc keeps cell text from breaking the Markdown table.
func esc(s string) string { return strings.ReplaceAll(s, "|", "\\|") }

// writeReport renders the results matrix as Markdown when REDTEAM_REPORT
// points at a file (set by `make redteam`). Normal `go test` runs only
// print to the test log.
func writeReport(t *testing.T) {
	t.Helper()
	path := os.Getenv("REDTEAM_REPORT")
	if path == "" {
		for _, r := range results {
			t.Logf("%-6s %-38s %-10s %s", r.id, r.attack, r.outcome, r.detail)
		}
		return
	}

	var b strings.Builder
	b.WriteString("# AgentVault red-team results\n\n")
	fmt.Fprintf(&b, "Generated by `make redteam` — %s, %s/%s.\n",
		time.Now().UTC().Format("2006-01-02 15:04 UTC"), runtime.GOOS, runtime.GOARCH)
	b.WriteString("Reproduce: `go test -v ./test/redteam/`. Attacks live in `test/redteam/`.\n\n")
	b.WriteString("| # | Attack | What it simulates | Stopped by | Result | Detail |\n")
	b.WriteString("|---|---|---|---|---|---|\n")
	for _, r := range results {
		fmt.Fprintf(&b, "| %s | %s | %s | %s | **%s** | %s |\n",
			r.id, esc(r.attack), esc(r.simulates), esc(r.layer), r.outcome, esc(r.detail))
	}
	b.WriteString(`
**Reading the matrix.** BLOCKED = the action never happened. DETECTED = the
action happened but is provably recorded (hash chain + session seal). KNOWN
GAP = a documented limitation of the userspace layers on platforms without a
kernel backend yet — see SECURITY.md; these rows are why Landlock/JobObjects
are the v0.3 roadmap, and they fail CI on macOS where the kernel backend
exists. SKIPPED = the attack does not apply to this platform.
`)
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o600); err != nil {
		t.Fatal(err)
	}
	t.Logf("wrote %s", path)
}
